### ISSUE TITLE
Clarify window rearranging algorithm

### ISSUE THREAD

**Issue by ihordv** [lingtjien/Grid-Tiling-Kwin#11]
Hi,
I really like this project, but can you clarify the window rearranging algorithm? I use default settings in following examples. So initially I open 4 windows:
```
1  2
3  4
```
Script works as expected if I drag one of windows to the neighbouring vertical/horizontal cell (windows switch places with each other):
```
3 -> 4 | 3 -> 1
-------|-------
 1  2  |  3  2 
 4  3  |  1  4 
```
However window don't just switch places if I drag window into opposite corner:
```
1 -> 4 | 2 -> 3
-------|-------
 2  4  |  3  1 
 3  1  |  2  4 
```
And I expected that following would happen:
```
1 -> 4 | 2 -> 3
-------|-------
 4  2  |  1  3 
 3  1  |  2  4 
```

Another situation which seems not not quite convenient is when I open 3 windows:
```
1  2
3  2
```
I don't understand what do I need to do to put window 2 in the corner and make either window 1 or 3 take half screen? If I drag window 1 into lower right corner, then columns switch places and 1 and 3 also switch places vertically:
```
 pre | post
-----|-----
1  2 | 2  3
3  2 | 2  1
```
Same thing happens even if I minimize large window 2, try to drag window 1 into lower right corner, then restore window 2:
```
 pre  | minimized | post | restore 
------|-----------|------|--------
 1  2 |   1  _    | _  3 |  2  3
 3  2 |   3  _    | _  1 |  2  1
```

**Comment by lingtjien** [comment]
Ah, I was expecting this ticket to eventually pop up. It's already on my to-do list but I'm currently very busy...

Anyways so, basically there is no 1 on 1 switch method when you drag clients around (I tried to implement it but it proved to be quite difficult or hacky at this moment, so I didn't do it yet).

But currently, it works as follows, if you drag a client, it will check if you dragged it outside of the `moveThreshold` * `clientSize` and if so switch the client with its neighbor in that direction which is equivalent to the global shortcut `Grid-Tiling: switch client *direction*` but if you drag the client outside of both the vertical and horizontal direction (diagonal) then it will basically do the switch two times one time in the horizontal direction and another time in the vertical direction. This is why you observe that 3 clients are switched in position when you do a diagonal client drag by mouse. This is not ideal as you've observed...

This would be solved by implementing a 1 on 1 switching method where the two clients are literally swapped, but this has some other complications which I didn't solve yet...

**Comment by lingtjien** [comment]
currently not, but I like the idea of being able to move clients within a virtual desktop instead of switching. So there's a few ways to handle failures. 

In your example if client 1 and 3 had a minSpace of 1/4 then since there are 2 columns, column 1 has a total space of 1/2 so client 1 + 3 would fully occupy this column already so you would not be able to move client 4 from column 2 to column 1.

So in this case, the new global shortcut of moving would fail. What would then be a more desired result?

1. the global shortcut does nothing as the first column is already full and thus trying to move clients from a different column to this column would not be possible.
2. the global shortcut falls back to the current switching method where it then attempts to switch the clients (or columns).

**Comment by neupsh** [comment]
I think both options are equally good. May be let users choose the desired behaviour through preferences and set "switching" (#2) as default so that users don't get confused when their shortcut don't do anything :)

**Comment by lingtjien** [comment]
I implemented a move shortcut (and dragging clients by mouse now attempts a move first too) in the dev branch. I did some basic testing but feel free to give it a try and see if you can break it. If nobody manages to break it in a week I'll merge it into master.

I left the old `swap left` and `swap right` still in the code but did not assign any shortcuts by default, personally, I like the new `move left` and `move right` shortcuts better since they fall back to swap anyways if they fail. So I'm debating about removing the `swap left` and `swap right` shortcuts, but if anyone would still rather use those then please let me know (and why preferably).

**Comment by lingtjien** [comment]
@ihordv I made an attempt to create a 1 on 1 switching method when dragging clients around by mouse, it should work even when you drag clients between physical screens and it should support minimized clients too. But I haven't tested it thoroughly but you can give it a try in the dev branch

**Comment by ihordv** [comment]
@lingtjien Thanks for implementation, but unfortunately I cannot test it as I don't have any KDE-based systems right now. I'll definitely give it a try once I have one, but probably not in the nearest future

**Comment by Nano-Ocelot** [comment]
@lingtjien I just looked into this and the new implementation is much much better.

**Comment by lingtjien** [comment]
@Nano-Ocelot Ah okay, I didn't think I accounted for moving to empty screens yet. I also noticed a few other problems, so I will have to fix that too. Multiscreen support is a bit difficult for me to debug since I don't have a second monitor on hand, so that takes a bit longer

**Comment by Nano-Ocelot** [comment]
No worries. I have a few other suggestions that would really enhance the
script that I assume are pretty feasible if you'd like to hear them
sometime. Anyway keep up the good work.

**Comment by lingtjien** [comment]
I think I fixed the moving to empty screen, but I didn't test it yet

You can always open a ticket if you have suggestions

**Comment by Nano-Ocelot** [comment]
I just tested it a few times and it seems the issue still persists after the latest update.

**Comment by lingtjien** [comment]
Alright, I'll have to test and debug it using a second monitor then

**Comment by duvholt** [comment]
I've also noticed issues with multiple monitors. The behavior is especially buggy when using three monitors. 

How do you debug this script? Adding a simple contributing guide in the readme would be really nice!

**Comment by lingtjien** [comment]
I borrowed my parent's tv for a little testing :)

I found that the KWin signals that I used didn't trigger when changing clients between physical screens only virtual desktops, so using the client signals now respectively should fix that and I forgot to add one more condition in the target checking for swapping. I think this should fix a lot of issues... please give it a try I will try it more thoroughly next week when I have access to a second monitor.
